### PR TITLE
Add optional extensions

### PR DESCRIPTION
**Pull request by munrocket**
How to use [extensions](https://www.w3.org/TR/WGSL/#enable-extensions-sec):

```wgsl
enable chromium_experimental_subgroups;
#define PI 3.14

@compute @workgroup_size(256)
#workgroup_count main 256 1 1
fn main(
  @builtin(global_invocation_id) global_id : vec3u,
  @builtin(subgroup_size) sg_size : u32,
  @builtin(subgroup_invocation_id) sg_id : u32
) {
      // TODO: Use subgroupBallot() and subgroupBroadcast()
}
```

The problem that wgpu [not supporting chromium extension](https://github.com/gfx-rs/wgpu/issues/5685) yet, but maybe we create device with web_sys?

Also it seems some errors introduced to wasm build after [79ad98d](https://github.com/compute-toys/wgpu-compute-toy/tree/79ad98d7f3002615fb75e6a6d97133e9db56f054) commit, @stefnotch can you please fix it? It is visible only with compute.toy website.

### CODE REVIEW

**Comment by stefnotch** [comment]
@munrocket Sure, how do I best locally reproduce the errors?

**Comment by munrocket** [comment]
@stefnotch you can replace wgpu-compute-toy folder in [compute.toys](https://github.com/compute-toys/compute.toys) than `yarn install` & `yarn dev`

**Comment by munrocket** [comment]
Btw #23 also opened error in web with timestamps that was fixed here in [de75501](https://github.com/compute-toys/wgpu-compute-toy/pull/24/commits/de755013a82f022d33d7d63ec3fdb2fb727bbd3e) by commenting it. So we should merge this PR for fixing web too. Timestamps need more general solution, I hope someday we will find it.

**Comment by davidar** [comment]
Thanks, I merged it manually with some minor changes, and also fixed wasm panicking over undefined canvas

**Pull request closed without merging**
