### PR TITLE
default mouse position in center of screen

### PR DESCRIPTION
**Pull request by munrocket**
This is very useful for camera controls.

Examples:
https://compute.toys/view/31
https://compute.toys/view/459

### CODE REVIEW

**Comment by davidar** [comment]
I think shadertoy defaults to zero so you can detect when the mouse has been used (eg some shaders will disable automatic rotation when that happens). Not sure if anyone is relying on that behaviour here yet though? Might just have to check the published shaders first to confirm

**Comment by munrocket** [comment]
Checked around 20 examples and no one using it.

But I found example where a guy commented mouse at all, because initialization not in center of a screen.
https://compute.toys/view/80

**Comment by munrocket** [comment]
Here something complicated with mouse exactly for that reason I guess. https://compute.toys/view/256
Maybe this is the only one example who will be affected.

**Comment by davidar** [comment]
Ok cool, thanks for checking!

**Pull request merged**
